# Generated by Django 4.2.21 on 2025-06-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('is_5g', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DimRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('regional_5g_coverage', models.FloatField()),
                ('subscribers_5g_million', models.FloatField()),
                ('avg_5g_speed_mbps', models.FloatField()),
                ('preference_5g_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
            ],
        ),
        migrations.CreateModel(
            name='SalesFactRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('market_share', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimregion')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimtime')),
            ],
        ),
        migrations.CreateModel(
            name='SalesFactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimproduct')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimtime')),
            ],
        ),
        migrations.CreateModel(
            name='SalesFact5G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimproduct')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimregion')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dimtime')),
            ],
        ),
    ]
